title: Office of Investigations
# Bind to all available IPs to enable connections over the local network
host: 0.0.0.0

# Defines post permalink structure only.
permalink: /posts/:year/:month/:day/:title
